{% set name = "pysumreg" %}
{% set version = "1.0.6" %}
{% set sha256 = "b195b27bcd6c8e1136f8a28ac726978f2a4cd79fa1dd7e32751fd0ede4346c7e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysumreg-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pysumreg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prjemian/pysumreg
  summary: Statistics of list of (x, y) pairs from calculator-style summation registers.
  license: EPL-2.0
  license_file: pysumreg/LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
