{% set name = "pysumreg" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysumreg-{{ version }}.tar.gz
  sha256: 6d2f602344e5b5344269dac0ba7a942d1a5ebc80d727e9c7ea8fa7131e4d671b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pysumreg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prjemian/pysumreg
  summary: Statistics of list of (x, y) pairs from calculator-style summation registers.
  license: EPL-2.0
  license_file: pysumreg/LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
